FROM balenalib/%%BALENA_MACHINE_NAME%%-debian-python:3-buster-build

RUN apt-get update && apt-get install -yq --no-install-recommends \
# linux-headers-$(uname -r) \
  && \
  apt-get clean && rm -rf /var/lib/apt/lists/*

RUN  pip install evdev

CMD [ "sleep", "84600"]