FROM balenalib/%%BALENA_MACHINE_NAME%%-debian-python:3-buster-build

RUN apt-get update && apt-get install -yq --no-install-recommends \
# linux-headers-$(uname -r) \
  && \
  apt-get clean && rm -rf /var/lib/apt/lists/*


# Copy requirements.txt first for better cache on later pushes
COPY requirements.txt requirements.txt

# pip install python deps from requirements.txt on the resin.io build server
RUN pip install -r requirements.txt

CMD [ "sleep", "84600"]